# SPDX-FileCopyrightText: The Gommitlint Action Authors
#
# SPDX-License-Identifier: CC0-1.0
name: Feature Suggestion
about: Suggest something for this project
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature suggestion!
        Headers with * are mandatory.

        Note: For features related to commit validation rules, please file an issue
        in the main [gommitlint repository](https://codeberg.org/itiquette/gommitlint/issues).
  - type: textarea
    id: problem
    attributes:
      label: What benefits does the suggestion solve?
      description: Please describe what benefits the feature suggestion would enable.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Feature suggestion description
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Anything else that you consider important for understanding your feature suggestion.
    validations:
      required: false
